<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<OutputType>Library</OutputType>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="Northwood.LabAPI" Version="1.1.4" />
	</ItemGroup>
	
	<ItemGroup>
	  <Reference Include="Assembly-CSharp">
	    <HintPath>$(SL_REFERENCES)\Assembly-CSharp.dll</HintPath>
	  </Reference>
	  <Reference Include="Mirror">
	    <HintPath>$(SL_REFERENCES)\Mirror.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityEngine.CoreModule">
	    <HintPath>$(SL_REFERENCES)\UnityEngine.CoreModule.dll</HintPath>
	  </Reference>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Copy SourceFiles="$(TargetDir)$(TargetName).dll" DestinationFolder="C:\Users\Kille\AppData\Roaming\SCP Secret Laboratory\LabAPI\plugins\global" />
	</Target>
</Project>